import { MatchEvent } from '@/types';
import { SeededRng } from '@/engine/rng';
import {
  INJURY_DURATION_WEIGHTS,
  RED_SUSPENSION_WEEKS,
  YELLOW_SUSPENSION_THRESHOLD,
  YELLOW_SUSPENSION_WEEKS,
} from '@/engine/balance';

export interface InjuryOutcome {
  playerId: number;
  weeks: number;
}

export interface SuspensionOutcome {
  playerId: number;
  weeks: number;
  reason: 'red' | 'yellow_accumulation';
}

const WEEK_INDEXES = INJURY_DURATION_WEIGHTS.map((_, i) => i + 1);

/** Samples a duration (weeks, 1..8) for each 'injury' event in this match. */
export function resolveMatchInjuries(events: MatchEvent[], rng: SeededRng): InjuryOutcome[] {
  const out: InjuryOutcome[] = [];
  for (const e of events) {
    if (e.type !== 'injury') continue;
    const weeks = rng.weightedPick(WEEK_INDEXES, INJURY_DURATION_WEIGHTS);
    out.push({ playerId: e.playerId, weeks });
  }
  return out;
}

/**
 * Suspensions generated by THIS match only:
 *  - each 'red' (direct or second-yellow) ⇒ RED_SUSPENSION_WEEKS.
 *  - yellow accumulation: cross a multiple of YELLOW_SUSPENSION_THRESHOLD ⇒
 *    YELLOW_SUSPENSION_WEEKS, using priorYellowsBySeason (yellows accrued BEFORE
 *    this match). Fires iff floor((prior+gained)/T) > floor(prior/T).
 * `rng` is accepted for signature symmetry/future variance; not consumed here.
 */
export function resolveMatchSuspensions(
  events: MatchEvent[],
  priorYellowsBySeason: Map<number, number>,
  rng: SeededRng,
): SuspensionOutcome[] {
  void rng;
  const out: SuspensionOutcome[] = [];

  // 1. Reds → fixed ban.
  for (const e of events) {
    if (e.type === 'red') {
      out.push({ playerId: e.playerId, weeks: RED_SUSPENSION_WEEKS, reason: 'red' });
    }
  }

  // 2. Yellow accumulation per player.
  const gainedByPlayer = new Map<number, number>();
  for (const e of events) {
    if (e.type === 'yellow') {
      gainedByPlayer.set(e.playerId, (gainedByPlayer.get(e.playerId) ?? 0) + 1);
    }
  }
  for (const [playerId, gained] of gainedByPlayer) {
    const prior = priorYellowsBySeason.get(playerId) ?? 0;
    const before = Math.floor(prior / YELLOW_SUSPENSION_THRESHOLD);
    const after = Math.floor((prior + gained) / YELLOW_SUSPENSION_THRESHOLD);
    if (after > before) {
      out.push({ playerId, weeks: YELLOW_SUSPENSION_WEEKS, reason: 'yellow_accumulation' });
    }
  }

  return out;
}
